/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CancellationRefundRouteImport } from './routes/cancellation-refund'
import { Route as IndexRouteImport } from './routes/index'

const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationRefundRoute = CancellationRefundRouteImport.update({
  id: '/cancellation-refund',
  path: '/cancellation-refund',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cancellation-refund': typeof CancellationRefundRoute
  '/checkout': typeof CheckoutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cancellation-refund': typeof CancellationRefundRoute
  '/checkout': typeof CheckoutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cancellation-refund': typeof CancellationRefundRoute
  '/checkout': typeof CheckoutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cancellation-refund'
    | '/checkout'
    | '/privacy-policy'
    | '/shipping-policy'
    | '/terms-conditions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cancellation-refund'
    | '/checkout'
    | '/privacy-policy'
    | '/shipping-policy'
    | '/terms-conditions'
  id:
    | '__root__'
    | '/'
    | '/cancellation-refund'
    | '/checkout'
    | '/privacy-policy'
    | '/shipping-policy'
    | '/terms-conditions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CancellationRefundRoute: typeof CancellationRefundRoute
  CheckoutRoute: typeof CheckoutRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-refund': {
      id: '/cancellation-refund'
      path: '/cancellation-refund'
      fullPath: '/cancellation-refund'
      preLoaderRoute: typeof CancellationRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CancellationRefundRoute: CancellationRefundRoute,
  CheckoutRoute: CheckoutRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  TermsConditionsRoute: TermsConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
